{
 "title": "percent loss",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Distribution 01-10-90-99 quantile",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfTenMinutes(dt)) as time,\n  quantile(0.01)(ping_time_ms) quantile001, quantile(0.05)(ping_time_ms) quantile005,\n  quantile(0.10)(ping_time_ms) quantile010, quantile(0.25)(ping_time_ms) quantile025, \n  quantile(0.50)(ping_time_ms) quantile050, quantile(0.75)(ping_time_ms) quantile075, \n  quantile(0.90)(ping_time_ms) quantile090, quantile(0.95)(ping_time_ms) quantile095, \n  quantile(0.99)(ping_time_ms) quantile099\nFROM default.ping_times_collect\nWHERE $__timeFilter(toStartOfHour(dt))\nGROUP BY time\nORDER BY time ASC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Distribution 10-90 quantile",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfHour(dt)) as time,\n  quantile(0.01)(ping_time_ms) quantile001, quantile(0.05)(ping_time_ms) quantile005,\n  quantile(0.10)(ping_time_ms) quantile010, quantile(0.25)(ping_time_ms) quantile025, \n  quantile(0.50)(ping_time_ms) quantile050, quantile(0.75)(ping_time_ms) quantile075, \n  quantile(0.90)(ping_time_ms) quantile090, quantile(0.95)(ping_time_ms) quantile095, \n  quantile(0.99)(ping_time_ms) quantile099\nFROM default.ping_times_collect\nWHERE $__timeFilter(toStartOfHour(dt))\nGROUP BY time\nORDER BY time ASC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Amount of measures by hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfHour(dt)) as time,\n  count()\nFROM default.ping_times_collect\nWHERE $__timeFilter(toStartOfHour(dt))\nGROUP BY time\nORDER BY time ASC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Loss % by 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfTenMinutes(dt)) as time,\n  countIf(ping_time_ms>800)/count() time1\nFROM default.ping_times_collect\nWHERE $__timeFilter(toStartOfTenMinutes(dt))\nGROUP BY time\nORDER BY time ASC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Loss % by hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfHour(dt)) as time,\n  countIf(ping_time_ms>800)/count() time1\nFROM default.ping_times_collect\nWHERE $__timeFilter(toStartOfHour(dt))\nGROUP BY time\nORDER BY time ASC\nLIMIT 1000"
    }
   ]
  }
 ]
}